WEAPONS = [
    "reaver",
    "prime",
    "mystbloom",
    "elderflame",
    "glitchpop",
    "nebula",
    "oni",
    "prism",
    "sovereign",
    "araxys",
    "arcane",
    "spline",
    "smite",
    "ego",
    "g.u.n",
    "singularity",
    "sensation",
    "kuronami",
    "blackthorn",
    "ayakashi",
    "divergence",
    "prelude to chaos",
    "gaia's vengeance",
    "neo frontier",
    "cyrax",
    "cyrostasis",
    "forsaken",
]
